name: Audit/lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Install
      run: yarn install
      working-directory: './app'
      
    - name: Audit
      run: yarn audit --groups dependencies
      working-directory: './app'
      
    - name: Lint
      run: yarn lint
      working-directory: './app'
        
